export const COULD_NOT_CONNECT = 'COULD NOT CONNECT';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const USER_LOADING = 'USER_LOADING';
export const USER_FOUND = 'USER_FOUND';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';

export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const CHANGE_PASS_LOADING = 'CHANGE_PASS_LOADING';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_ERROR = 'CHANGE_PASS_ERROR';

export const GET_PROJECT_LOADING = 'GET_PROJECT_LOADING';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR';

export const PROJECT_LOADING = 'PROJECT_LOADING';
export const PROJECT_GETALL = 'PROJECT_GETALL';
export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_REMOVE = 'PROJECT_REMOVE';
export const PROJECT_ERROR = 'PROJECT_ERROR';

export const TASK_LOADING = 'TASK_LOADING';
export const TASK_ERROR = 'TASK_ERROR';
export const TASK_GET = 'TASK_GET';
export const TASK_CREATE = 'TASK_CREATE';
export const TASK_UPDATE = 'TASK_UPDATE';
export const TASK_REMOVE = 'TASK_REMOVE';

export const PROJECT_MEMBERS_LOADING = 'PROJECT_MEMBERS_LOADING';
export const PROJECT_MEMBERS_ERROR = 'PROJECT_MEMBERS_ERROR';
export const PROJECT_MEMBERS_GET = 'PROJECT_MEMBERS_GET';
export const PROJECT_MEMBERS_ADD = 'PROJECT_MEMBERS_ADD';
export const PROJECT_MEMBERS_REMOVE = 'PROJECT_MEMBERS_REMOVE';

export const TASK_MESSAGE_LOADING = 'TASK_MESSAGE_LOADING';
export const TASK_MESSAGE_ERROR = 'TASK_MESSAGE_ERROR';
export const TASK_MESSAGE_GET = 'TASK_MESSAGE_GET';
export const TASK_MESSAGE_ADD = 'TASK_MESSAGE_ADD';

export const TASK_POST_MESSAGE_LOADING = 'TASK_POST_MESSAGE_LOADING';
export const TASK_POST_MESSAGE_SUCCESS = 'TASK_POST_MESSAGE_SUCCESS';
export const TASK_POST_MESSAGE_ERROR = 'TASK_POST_MESSAGE_ERROR';

export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_GET = 'NOTIFICATION_GET';
export const NOTIFICATION_CREATE = 'NOTIFICATION_CREATE';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
